accounts/urls.py
from django.urls import path
from . import views
from .views import dashboard_admin, admin_registration


app_name = "accounts"

urlpatterns = [
    path('perfil_usuario', views.perfil_usuario, name='perfil_usuario'),
    path('editar_perfil', views.editar_perfil, name='editar_perfil'),
    path('vista_admin', views.admin_registration, name='vista_admin'),
    # path('admin/register/', admin_registration, name='admin_registration'),
    path('dashboard', dashboard_admin, name='dashboard'),
    #crud
    path('actualizar', views.actualizar, name='actualizar'),
    path('listar', views.listar , name='listar'),
    path('agregar', views.agregar, name='agregar'),
    path('eliminar', views.eliminar, name='eliminar'),
  
    
    
    
]

api/urls.py
from django.urls import path, include
from rest_framework import routers
from . import views



router = routers.DefaultRouter()
router.register(r'players', views.PlayerViewSet)
router.register(r'noticias', views.NoticiasViewSet)
router.register(r'teams', views.TeamsViewSet)
router.register(r'market', views.MarketViewSet)
router.register(r'torneo', views.TorneoViewSet)




urlpatterns = [
   # path('', views.getData),
    #path('add/', views.addPlayer),
    path('', include(router.urls)),
]

blog/urls.py
from django.urls import path
from .views import category, autor, HomeListView, PostDetailView, PostCreateView, PostUpdateView, PostDeleteView

app_name="blog"

urlpatterns = [
    path('', HomeListView.as_view(), name='blog'),
    #Detalle post
    path('post/<pk>/', PostDetailView.as_view(), name='detalle_post'),
    #crear post
    path('create/', PostCreateView.as_view() , name='create'),
    #editar post
    path('update/<int:pk>', PostUpdateView.as_view() , name='update'),
    #eliminar post
    path('delete/<int:pk>', PostDeleteView.as_view() , name='delete'),
    
    
    path('category/<int:category_id>/', category, name='category'),
    path('autor/<int:autor_id>/', autor, name='autor'),
    
]

core/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from django.urls.conf import include

from .views import HomeView
from hltv import views

from rest_framework.documentation import include_docs_urls


urlpatterns = [
    path('admin/', admin.site.urls),
    path('csinfo/', include('csinfo.urls', namespace="csinfo")),
    path('accounts/', include('allauth.urls')),
    path('users/', include('accounts.urls', namespace='users')),
    path('blog/', include('blog.urls', namespace='blog')),
    

    path("__reload__/", include("django_browser_reload.urls")),
    path('', HomeView.as_view(), name="home"),
    path('hltv/', include('hltv.urls', namespace="hltv")),

    path('api/', include('api.urls')),
    path('docs/', include_docs_urls(title='Api CSinfo Documentation'))
    
]

if settings.DEBUG:
    urlpatterns+= static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns+= static(settings.STATIC_URL, document_root=settings.STATIC_URL)

hltv/urls.py
from django.urls import path

from . import views

app_name="hltv"

urlpatterns = [
    path('stats', views.stats, name='stats'),
    path('list_players', views.list_players, name='list_players'),
    path('noticias', views.noticias, name='noticias'),
    path('teams', views.teams, name='teams'),
    path('get_noticias', views.get_noticias, name='get_noticias'),
    path('get_teams', views.get_teams, name='get_teams'),
    path('market', views.market, name='market'),
    path('get_market', views.get_market, name='get_market'),
    
]

blog/models.py
from django.db import models

from ckeditor.fields import RichTextField


from django.conf import settings



# Create your models here.

class Category (models.Model):
	name = models.CharField(max_length=200, unique=True, verbose_name='Nombre')
	active = models.BooleanField(default=True, verbose_name='Activo')
	created = models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')
	updated = models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')

	class Meta:
		verbose_name = 'Categoría'
		verbose_name_plural = 'Categorías'
		ordering = ['name']

	def __str__(self):
		return self.name
	
# MODELO DE ETIQUETAS
	
class Tag (models.Model):
	name = models.CharField(max_length=200, unique=True, verbose_name='Nombre')
	active = models.BooleanField(default=True, verbose_name='Activo')
	created = models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')
	updated = models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')

	class Meta:
		verbose_name = 'Etiqueta'
		verbose_name_plural = 'Etiquetas'
		ordering = ['name']

	def __str__(self):
		return self.name


class Post(models.Model):
    title = models.CharField(max_length=100, verbose_name='Titulo')
    excerpt = models.TextField(verbose_name='Bajada')
    content = RichTextField(verbose_name='Contenido')
    image = models.ImageField(upload_to='posts', null=True, blank=True, verbose_name='Imagen')
    published = models.BooleanField(default=False, verbose_name='Publicado')

    #CAMPOS CON RELACIONES
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='get_posts', verbose_name='Categoría')
    tags = models.ManyToManyField(Tag, verbose_name='Etiquetas')
    autor =  models.ForeignKey(settings.AUTH_USER_MODEL, related_name='get_posts', on_delete=models.CASCADE)

    created = models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')
    updated = models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')


class Meta:
        verbose_name = 'Publicación'
        verbose_name_plural = 'Publicaciones'
        ordering = ['-created']

        def __str__(self):
            return self.title
	
class About(models.Model):
	description = models.CharField(max_length=350, verbose_name='Descripción')
	created = models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')
	updated = models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')

	class Meta:
		verbose_name = 'Acerca de'
		verbose_name_plural = 'Acerca de Nosotros'
		ordering = ['-created']

	def __str__(self):
		return self.description

hltv/models.py
from django.db import models
from model_utils import Choices
from django.conf import settings
import os 






class Player(models.Model):
    id = models.AutoField(primary_key=True)
    nickname = models.CharField(max_length=100)
    team = models.CharField(max_length=100)
    mapsPlayed = models.IntegerField(verbose_name='mapsplayed')
    kd = models.DecimalField(verbose_name='kd', max_digits=5, decimal_places=2)
    rating = models.DecimalField(verbose_name='rating', max_digits=5, decimal_places=2)

    def __str__(self):
        return self.nickname

    
class Teams(models.Model):
    id_team = models.AutoField(primary_key=True)
    nameTeam = models.CharField(max_length=50)
    ranking = models.IntegerField(verbose_name='ranking')
    logo = models.ImageField(upload_to='logos/')
    players = models.CharField(max_length=250)

    def __str__(self):
        return self.nameTeam



class Noticias(models.Model):
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=250)
    link = models.URLField(verbose_name='link')
    time = models.DateTimeField(verbose_name='time')

    def __str__(self):
        return self.title
    


    
class Market(models.Model):
    WTYPE_1 = 'Pistols'
    WTYPE_2 = 'Rifles'
    WTYPE_3 = 'SMG'
    WTYPE_4 = 'Shotguns'
    WTYPE_5 = 'Knifes'
    WTYPE_6 = 'Gloves'

    CHOICES = (
        (WTYPE_1, 'Pistols'),
        (WTYPE_2, 'Rifles'),
        (WTYPE_3, 'SMG'),
        (WTYPE_4, 'Shotguns'),
        (WTYPE_5, 'Knifes'),
        (WTYPE_6, 'Gloves'),
    )
    choice_field = models.CharField(max_length=50, choices=CHOICES)
    nameSkin = models.CharField(max_length=100)
    DWEAPON1 = 'Classified'
    DWEAPON2 = 'Restricted'
    DWEAPON3 = 'Mil-spec'
    DWEAPON4 = 'Covert'
    DWEAPON5 = 'Industrial'
    DWEAPON6 = 'Consumer'

    OPCIONESARMAS = (
        (DWEAPON1, 'Classified'),
        (DWEAPON2, 'Restricted'),
        (DWEAPON3, 'Mil-spec'),
        (DWEAPON4, 'Covert'),
        (DWEAPON5, 'Industrial'),
        (DWEAPON6, 'Consumer'),
    )
    defWeapon = models.CharField(max_length=50, choices=OPCIONESARMAS)

    QWEAPON1 = 'FN'
    QWEAPON2 = 'MW'
    QWEAPON3 = 'FT'
    QWEAPON4 = 'WW'
    QWEAPON5 = 'BS'
    QWEAPON6 = 'ST FN'
    QWEAPON7 = 'ST MW'
    QWEAPON8 = 'ST FT'
    QWEAPON9 = 'ST WW'
    QWEAPON10 = 'ST BS'

    OPCIONESQUALITY = (
        (QWEAPON1, 'FN'),
        (QWEAPON2, 'MW'),
        (QWEAPON3, 'FT'),
        (QWEAPON4, 'WW'),
        (QWEAPON5, 'BS'),
        (QWEAPON6, 'ST FN'),
        (QWEAPON7, 'ST MW'),
        (QWEAPON8, 'ST FT'),
        (QWEAPON9, 'ST WW'),
        (QWEAPON10, 'ST BS'),
    )
    qualityWeapon = models.CharField(max_length=50, choices=OPCIONESQUALITY)
    containerWeapon = models.CharField(max_length=100)
    collectionsWeapon = models.CharField(max_length=100)
    imagenArma = models.ImageField(upload_to='weapons/')
    precioArma = models.DecimalField(verbose_name='precioarma', max_digits=5, decimal_places=2)
    def __str__(self):
        return self.choice_field + ' | ' + self.nameSkin 


""" class Armas(models.Model):
    market = models.OneToOneField(Market, on_delete=models.CASCADE)
    nameSkin = models.CharField(max_length=100)
    DWEAPON1 = 'Classified'
    DWEAPON2 = 'Restricted'
    DWEAPON3 = 'Mil-spec'
    DWEAPON4 = 'Covert'
    DWEAPON5 = 'Industrial'
    DWEAPON6 = 'Consumer'

    OPCIONESARMAS = (
        (DWEAPON1, 'Classified'),
        (DWEAPON2, 'Restricted'),
        (DWEAPON3, 'Mil-spec'),
        (DWEAPON4, 'Covert'),
        (DWEAPON5, 'Industrial'),
        (DWEAPON6, 'Consumer'),
    )
    defWeapon = models.CharField(max_length=50, choices=OPCIONESARMAS)

    QWEAPON1 = 'FN'
    QWEAPON2 = 'MW'
    QWEAPON3 = 'FT'
    QWEAPON4 = 'WW'
    QWEAPON5 = 'BS'
    QWEAPON6 = 'ST FN'
    QWEAPON7 = 'ST MW'
    QWEAPON8 = 'ST FT'
    QWEAPON9 = 'ST WW'
    QWEAPON10 = 'ST BS'

    OPCIONESQUALITY = (
        (QWEAPON1, 'FN'),
        (QWEAPON2, 'MW'),
        (QWEAPON3, 'FT'),
        (QWEAPON4, 'WW'),
        (QWEAPON5, 'BS'),
        (QWEAPON6, 'ST FN'),
        (QWEAPON7, 'ST MW'),
        (QWEAPON8, 'ST FT'),
        (QWEAPON9, 'ST WW'),
        (QWEAPON10, 'ST BS'),
    )
    qualityWeapon = models.CharField(max_length=50, choices=OPCIONESQUALITY)
    containerWeapon = models.CharField(max_length=100)
    collectionsWeapon = models.CharField(max_length=100)
    imagenArma = models.ImageField(upload_to='media')
    precioArma = models.DecimalField(verbose_name='precioarma', max_digits=5, decimal_places=2)
    
    def __str__(self):
        return self.nameSkin  """





""" class Torneos(models.Model):
    nombreTorneo = models.CharField(max_length=100)
    locacionTorneo = models.CharField(max_length=100)
    teamsParticipando = models.IntegerField()
    premio = models.IntegerField()
    fechaInicio = models.DateField(verbose_name='fecha_inicio' )
    fechaTermino = models.DateField(verbose_name='fecha_termino')
    topPlayer = models.CharField(max_length=100)
    teamCampeon = models.CharField(max_length=100)

    def __str__(self):
        return self.nombreTorneo  """
    

blog/forms.py
from django import forms
from .models import Post

class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ['title', 'excerpt', 'content', 'image', 'category', 'tags']

        widgets = {
            'title':forms.TextInput(attrs={'class':'form-control'}),
            'excerpt':forms.Textarea(attrs={'class':'form-control'}),
            'content':forms.Textarea(attrs={'class':'form-control'}),
            'image':forms.ClearableFileInput(attrs={'class':'form-control'}),
            'category':forms.Select(attrs={'class':'form-control'}),
            'tags':forms.SelectMultiple(attrs={'class':'form-control'}),
        }

blog/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Post, Category
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.conf import settings
from django.contrib.auth.models import User, AbstractUser
from django.contrib.auth import get_user_model
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView

from .forms import PostForm

@login_required
def crear_post(request):
    if request.method == 'POST':
        titulo = request.POST['titulo']
        descripcion = request.POST['descripcion']
        autor = request.user
        post = Post(titulo=titulo, descripcion=descripcion, autor=autor)
        post.save()
    return render(request, 'pages/crear_post.html')
#Home del blog
class HomeListView(ListView):
    model = Post
    paginate_by = 3
    template_name = 'pages/blog.html'

    def get_queryset(self):
        return Post.objects.filter(published=True)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

# Detalle del Post
class PostDetailView(DetailView):
    model = Post
    template_name = 'pages/detalle_post.html'

# Filtrado por Categoría
def category(request, category_id):
    try:
        category = get_object_or_404(Category, id=category_id)
        return render(request, 'pages/category.html', {'category':category})    
    except:
        return render(request, 'pages/404.html')
    

    

def autor(request, autor_id):
 
        autor = get_object_or_404(get_user_model(), id=autor_id)
        
        return render(request, 'pages/autor.html', {'autor':autor})    
   

#crear post
class PostCreateView(CreateView):
    model = Post
    form_class = PostForm

    def form_valid(self, form):
        form.instance.autor = self.request.user
        return super().form_valid(form)

    success_url = reverse_lazy('blog:blog') 


#Editar post
class PostUpdateView(UpdateView):
    model = Post
    form_class = PostForm
    template_name_suffix = '_update_form'
    def form_valid(self, form):
        form.instance.autor = self.request.user
        return super().form_valid(form)
    def get_success_url(self):
        return reverse_lazy('blog:update', args=[self.object.id]) + '?ok'

#Delete post
class PostDeleteView(DeleteView):
    model = Post
    success_url = reverse_lazy('blog:blog') 

hltv/views.py
from django.shortcuts import render, redirect
from django.http.response import JsonResponse
from hltv.models import Player, Noticias, Teams, Market
import requests

from django.conf import settings

# Create your views here.

#def players(request):
#    #pull data from third party rest api
#    response = requests.get('https://hltv-api.vercel.app/api/player.json')
#    #convert reponse data into json
#    players = response.json()
#    print(players)
#    return render(request, "pages/hltv.html", {'players': players})
#    pass


#def stats(request):
#    nickname = request.GET.get('nickname')
#    if not request.user.is_authenticated:
#        return redirect(f"{settings.LOGIN_URL}?next={request.path}")
#    jugadores = Player.objects.all()
#    return render(request, 'pages/stats.html', {'jugadores': jugadores})

# STATS DE JUGADORES
def stats(request):
    return render(request, 'pages/stats.html')

def list_players(_request):
    players = list(Player.objects.values())
    data = {'players': players}
    return JsonResponse(data)

#NOTICIAS CSGO
def get_noticias(_request):
    noticias = list(Noticias.objects.values())
    if (len(noticias)>0):
        data={'message': "Success", 'noticias': noticias }
    else:
        data = {'message': 'NotFound'}
    return JsonResponse(data)
def noticias(request):
    if not request.user.is_authenticated:
        return redirect(f"{settings.LOGIN_URL}?next={request.path}")
    #noticias = Noticias.objects.all()
    #return render(request, 'pages/noticias.html', {'noticias': noticias} )
    return render(request, 'pages/noticias.html')

 #MARKET CSGO
def get_market(_request):
    market = list(Market.objects.values())
    if (len(market)>0):
        data={'message': "Success", 'market': market }
    else:
        data = {'message': 'NotFound'}
    return JsonResponse(data)



def market(request):
    #if not request.user.is_authenticated:
        #return redirect(f"{settings.LOGIN_URL}?next={request.path}")
    #noticias = Noticias.objects.all()
    #return render(request, 'pages/noticias.html', {'noticias': noticias} )
    return render(request, 'pages/market.html')






#TEAMS CSGO
def get_teams(_request):
    teams = list(Teams.objects.values()) 
    if (len(teams)>0):
        data={'message': "Success", 'teams': teams }
    else:
        data = {'message': 'No hay registros'}
    return JsonResponse(data)

def teams(request):    
    return render(request, 'pages/teams.html' )
    

templates/pages/category.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    
    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous" />
    <!-- DataTable.js -->
    <link rel="stylesheet" href="https://cdn.datatables.net/1.13.1/css/dataTables.bootstrap5.min.css" />
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css" />
    <link href="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.6.5/flowbite.min.css"  rel="stylesheet" />
    <link rel="stylesheet" type="css" href="{% static 'css/bootstrap.min.css' %}">
    
  
  
  </head>
  <br>

  <div class="alert alert-success" role="alert">
    Todos los Posts con la categoría: <strong>{{ category.name }}</strong>
  </div>


{% for post in category.get_posts.all %}

    <div class="card mb-3">
        <div class="row g-0">
            <div class="col-md-5">
                <img src={{ post.image.url }} class="img-fluid rounded-start" alt="...">
            </div>
            <div class="col-md-7">
                <div class="card-body">
                    <strong class="d-inline-block mb-2 text-primary">{{ post.category }}</strong>
                    <h4 class="mb-0">{{ post.title }}</h4>
                    <div class="mb-1 text-muted">{{ post.created|date:"d M Y" }}</div>
                    <p class="card-text mb-auto">{{ post.excerpt }}</p>
                    <p class="card-text"><small class="text-muted"><a href={% url 'blog:detalle_post' post.id %} class="stretched-link">Seguir leyendo</a></small></p>
                </div>
            </div>
        </div>
    </div>

{% empty %}

    <div class="alert alert-danger" role="alert">
        <strong>No existen Posts con la categoría: {{ category.name }}</strong>
    </div>

{% endfor %}



<hr>

{% if request.path != '/' %}
    <div class="my-3">
        <a class="btn btn-success rounded-pill" href={% url 'blog:blog' %}>Volver al inicio del blog</a>
    </div>
{% endif %}
{% endblock %}

templates/pages/dashboard.html
{% extends 'base.html' %}

{% load static %}

{% block navbar %} 
{% include 'components/navbaradmin.html' %}
{% endblock navbar %}

{% block content %}
<head>
  <meta charset="UTF-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  
  <!-- Bootstrap -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous" />
  <!-- DataTable.js -->
  <link rel="stylesheet" href="https://cdn.datatables.net/1.13.1/css/dataTables.bootstrap5.min.css" />
  <!-- Font Awesome -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css" />
  <link href="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.6.5/flowbite.min.css"  rel="stylesheet" />
  


</head>
<br>

  <div class="container-fluid bg-light rounded p-3">
    <div class="row">
      <aside class="col-md-3">
        <h2>Menú de Administrador</h2>
        <ul class="nav flex-column">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'users:listar' %}"><i class="fa fa-user"></i>Listar</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'users:agregar' %}"><i class="fa fa-user-plus"></i>Agregar</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'users:actualizar' %}"><i class="fa fa-user-edit"></i>Actualizar</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'users:eliminar' %}"><i class="fa fa-user-times"></i>Eliminar</a>
          </li>
        </ul>
      </aside>
      
      <main class="col-md-9">
        <section>
          <h2>Bienvenido al Panel de Control de Administrador</h2>
          <p>Aquí puedes administrar los usuarios y la configuración del sitio.</p>
        </section>
        
        <!-- Resto del contenido del dashboard -->
      </main>
    </div>
  </div>
  
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>




  

{% endblock content %}



{% block javascript %} 
<script
      type="text/javascript"
      src="https://cdnjs.cloudflare.com/ajax/libs/jszip/2.5.0/jszip.min.js"
    ></script>
    <script
      type="text/javascript"
      src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/pdfmake.min.js"
    ></script>
    <script
      type="text/javascript"
      src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/vfs_fonts.js"
    ></script>
    <script
      type="text/javascript"
      src="https://cdn.datatables.net/1.13.1/js/jquery.dataTables.min.js"
    ></script>
    <script
      type="text/javascript"
      src="https://cdn.datatables.net/1.13.1/js/dataTables.bootstrap5.min.js"
    ></script>
    <script
      type="text/javascript"
      src="https://cdn.datatables.net/buttons/2.3.3/js/dataTables.buttons.min.js"
    ></script>
    <script
      type="text/javascript"
      src="https://cdn.datatables.net/buttons/2.3.3/js/buttons.bootstrap5.min.js"
    ></script>
    <script
      type="text/javascript"
      src="https://cdn.datatables.net/buttons/2.3.3/js/buttons.html5.min.js"
    ></script>
    <script
      type="text/javascript"
      src="https://cdn.datatables.net/buttons/2.3.3/js/buttons.print.min.js"
    ></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.6.5/flowbite.min.js"></script>

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.min.js" integrity="sha384-fbbOQedDUMZZ5KreZpsbe1LCZPVmfTnH7ois6mU1QK+m14rQ1l2bGBq41eYeM/fS" crossorigin="anonymous"></script>

    

{% endblock javascript %}

templates/pages/detalle_post.html
{% extends 'base.html' %}
{% load static %}
{% block navbar %} 
{% include 'components/navbar.html' %}
{% endblock navbar %}

{% block content %}
<br>
<article class="blog-post bg-gray-200 p-3 rounded">
    <div class="col-auto d-none d-lg-block">
        <img src={{ post.image.url }} class="img-fluid" alt="">
    </div>

    <strong class="d-inline-block mb-2 mt-3 text-primary"><a href={% url 'blog:category' post.category.id %}>{{ post.category }}</a></strong>
    <h2 class="blog-post-title mb-1">{{ post.title }}</h2>
    <p class="blog-post-meta">{{ post.created|date:"d M Y" }} por <a href={% url 'blog:autor' post.autor.id %}>{{ post.autor }}</a></p>

    <p class="lead my-3">{{ post.excerpt }}</p>
    <hr>
    <p>{{ post.content | safe }}</p>

    <hr>

    <strong>Etiquetas:</strong>
    {% for tag in post.tags.all %}
        <span class="badge text-bg-info">{{ tag.name|upper }}</span>
    {% endfor %}


<div class="my-3">
    <a class="btn btn-success rounded-pill" href={% url 'blog:blog' %}>Volver al Inicio</a>
    {% if request.user == post.autor %}
    <a class="btn btn-danger rounded-pill float-end" href={% url 'blog:delete' post.id %}>Eliminar</a>
    <a class="btn btn-info rounded-pill float-end" href={% url 'blog:update' post.id %}>Editar</a>
    {% endif %}
</div>
</article>

{% endblock %}

templates/pages/market.html
{% extends 'base.html' %}

{% load static %}

{% block navbar %} 
{% include 'components/navbar.html' %}
{% endblock navbar %}

{% block content %}
<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    
    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous" />
    <!-- DataTable.js -->
    <link rel="stylesheet" href="https://cdn.datatables.net/1.13.1/css/dataTables.bootstrap5.min.css" />
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css" />
    
</head>

<div class="container mt-5">

    <section>
        <h1 class="text-black text-center font-black text-5xl ">Market Counter-Strike</h1><br>
      <div class="row" id="marketItems"></div>
    </section>

  </div>









{% endblock content %}

{% block footer %} 
{% include 'components/footer.html' %}
{% endblock footer %}


{% block javascript %} 
<script src="{% static 'js/market.js' %}"></script>
{% endblock javascript %}