accounts/urls.py
from django.urls import path
from . import views
from .views import dashboard_admin, admin_registration


app_name = "accounts"

urlpatterns = [
    path('perfil_usuario', views.perfil_usuario, name='perfil_usuario'),
    path('editar_perfil', views.editar_perfil, name='editar_perfil'),
    path('vista_admin', views.admin_registration, name='vista_admin'),
    # path('admin/register/', admin_registration, name='admin_registration'),
    path('dashboard', dashboard_admin, name='dashboard'),
    #crud
    path('actualizar', views.actualizar, name='actualizar'),
    path('listar', views.listar , name='listar'),
    path('agregar', views.agregar, name='agregar'),
    path('eliminar', views.eliminar, name='eliminar'),
  
    
    
    
]

api/urls.py
from django.urls import path, include
from rest_framework import routers
from . import views



router = routers.DefaultRouter()
router.register(r'players', views.PlayerViewSet)
router.register(r'noticias', views.NoticiasViewSet)
router.register(r'teams', views.TeamsViewSet)
router.register(r'market', views.MarketViewSet)
router.register(r'torneo', views.TorneoViewSet)




urlpatterns = [
   # path('', views.getData),
    #path('add/', views.addPlayer),
    path('', include(router.urls)),
]

blog/urls.py
from django.urls import path
from .views import category, autor, HomeListView, PostDetailView, PostCreateView, PostUpdateView, PostDeleteView

app_name="blog"

urlpatterns = [
    path('', HomeListView.as_view(), name='blog'),
    #Detalle post
    path('post/<pk>/', PostDetailView.as_view(), name='detalle_post'),
    #crear post
    path('create/', PostCreateView.as_view() , name='create'),
    #editar post
    path('update/<int:pk>', PostUpdateView.as_view() , name='update'),
    #eliminar post
    path('delete/<int:pk>', PostDeleteView.as_view() , name='delete'),
    
    
    path('category/<int:category_id>/', category, name='category'),
    path('autor/<int:autor_id>/', autor, name='autor'),
    
]

core/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from django.urls.conf import include

from .views import HomeView
from hltv import views

from rest_framework.documentation import include_docs_urls


urlpatterns = [
    path('admin/', admin.site.urls),
    path('csinfo/', include('csinfo.urls', namespace="csinfo")),
    path('accounts/', include('allauth.urls')),
    path('users/', include('accounts.urls', namespace='users')),
    path('blog/', include('blog.urls', namespace='blog')),
    

    path("__reload__/", include("django_browser_reload.urls")),
    path('', HomeView.as_view(), name="home"),
    path('hltv/', include('hltv.urls', namespace="hltv")),

    path('api/', include('api.urls')),
    path('docs/', include_docs_urls(title='Api CSinfo Documentation'))
    
]

if settings.DEBUG:
    urlpatterns+= static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns+= static(settings.STATIC_URL, document_root=settings.STATIC_URL)

csinfo/urls.py
from django.urls import path
from . import views

app_name="csinfo"

urlpatterns = [
    path('major', views.major, name='major'),
    
]

hltv/urls.py
from django.urls import path

from . import views

app_name="hltv"

urlpatterns = [
    path('stats', views.stats, name='stats'),
    path('list_players', views.list_players, name='list_players'),
    path('noticias', views.noticias, name='noticias'),
    path('teams', views.teams, name='teams'),
    path('get_noticias', views.get_noticias, name='get_noticias'),
    path('get_teams', views.get_teams, name='get_teams'),
    path('market', views.market, name='market'),
    path('get_market', views.get_market, name='get_market'),
    
]

templates/components/footer.html
<footer class="footer bg-dark text-center text-white">
    <!-- Grid container -->
    <div class="sticky container p-4 pb-0">
      <!-- Section: Social media -->
      <section class="mb-4">
        <!-- Facebook -->
        <a class="btn text-white" style="background-color: #3b5998;" href="#!" role="button">
          <i class="fab fa-facebook-f"></i>
        </a>
  
        <!-- Twitter -->
        <a class="btn text-white" style="background-color: #55acee;" href="#!" role="button">
          <i class="fab fa-twitter"></i>
        </a>
  
        <!-- Google -->
        <a class="btn text-white" style="background-color: #dd4b39;" href="#!" role="button">
          <i class="fab fa-google"></i>
        </a>

        <!-- Instagram -->
        <a class="btn text-white" style="background-color: #ac2bac;" href="#!" role="button">
        <i class="fab fa-instagram"></i>
        </a>
  
        <!-- Linkedin -->
        <a class="btn text-white" style="background-color: #0082ca;" href="#!" role="button">
          <i class="fab fa-linkedin-in"></i>
        </a>
  
        <!-- Github -->
        <a class="btn text-white" style="background-color: #333333;" href="#!" role="button">
          <i class="fab fa-github"></i>
        </a>
        <!-- Reddit -->
        <a class="btn text-white" style="background-color: #ff4500;" href="#!" role="button">
          <i class="fab fa-reddit-alien"></i>
        </a>
        <!-- Youtube -->
        <a class="btn text-white" style="background-color: #ed302f;" href="#!" role="button">
          <i class="fab fa-youtube"></i>
        </a>
      </section>
      <!-- Section: Social media -->
    </div>
    <!-- Grid container -->
  
    <!-- Copyright -->
    <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
      ©
      <a class="text-white" href="#">Csinfo</a>
    </div>
    <!-- Copyright -->
  </footer>

templates/components/navbar.html
{% load static %}
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container-fluid">
        <a href="{% url 'home' %}" class="flex items-center">
          <img class="h-8 w-auto" src="{% static 'images/logo.png' %}" alt="CSinfo">
          
        </a>
        {% if user.is_authenticated %}
      <div class="items-center justify-between w-5/6 md:flex md:w-auto">
        <ul class="navbar-nav">          
          <li class="nav-item">
            <button type="button" class="btn btn-outline-secondary btn-rounded" data-mdb-ripple-color="dark">
              <a href="{% url 'hltv:stats' %}" class="block text-white rounded hover:bg-gray-100 md:hover:bg-transparent
             md:hover:text-blue-700 md:p-0 dark:text-white md:dark:hover:text-blue-500 dark:hover:bg-gray-700 md:dark:hover:bg-transparent dark:border-gray-700"><i class="fa-solid fa-game-console-handheld-crank"></i> E-Sport</a>
            </button>              
          </li>
          <li class="nav-item">
            <button type="button" class="btn btn-outline-secondary btn-rounded" data-mdb-ripple-color="dark">
            <a href="{% url 'csinfo:major' %}" class="block text-white rounded hover:bg-gray-100 md:hover:bg-transparent
             md:hover:text-blue-700 md:p-0 dark:text-white md:dark:hover:text-blue-500 dark:hover:bg-gray-700 dark:hover:text-white
              md:dark:hover:bg-transparent dark:border-gray-700"><i class="fa-solid fa-trophy"></i> Torneos historicos</a>
            </button>
          </li>
          <li>
            <button type="button" class="btn btn-outline-secondary btn-rounded" data-mdb-ripple-color="dark">
            <a href="{% url 'hltv:teams' %}" class="block text-white rounded hover:bg-gray-100 md:hover:bg-transparent
             md:hover:text-blue-700 md:p-0 dark:text-white md:dark:hover:text-blue-500 dark:hover:bg-gray-700 dark:hover:text-white
              md:dark:hover:bg-transparent dark:border-gray-700"><i class="fa-solid fa-ranking-star"></i> Ranking teams</a>
            </button>
          </li>
            {% comment %} <li>
            <button type="button" class="btn btn-outline-secondary btn-rounded" data-mdb-ripple-color="dark">
            <a href="{% url 'hltv:market' %}" class="block text-white rounded hover:bg-gray-100 md:hover:bg-transparent md:hover:text-blue-700 md:p-0 dark:text-white
             md:dark:hover:text-blue-500 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700"><i class="fa-sharp fa-solid fa-store"></i>Market</a>
            </button>
            </li> {% endcomment %}
            <li>
              <button type="button" class="btn btn-outline-secondary btn-rounded" data-mdb-ripple-color="dark">
              <a href="{% url 'blog:blog' %}" class="block text-white rounded hover:bg-gray-100 md:hover:bg-transparent md:hover:text-blue-700 md:p-0 dark:text-white
               md:dark:hover:text-blue-500 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700"><i class="fa-sharp fa-solid fa-store"></i>Blog/Market</a>
              </button>
              </li>
          
        </ul>
      </div>
      {% else %}

      {% endif %}
      
        <div x-data="{open: false}" class="flex items-center">
          {% if user.is_authenticated %}
          <div class="flex -space-x-2">
            <div class="relative inline-block text-left">
              
              <div>
                <button @click="open=true" type="button" class="text-white bg-blue-700 hover:bg-blue-800 focus:outline-none focus:ring-4 focus:ring-blue-300 font-medium rounded-full text-sm px-5 py-2.5 text-center mr-2 mb-2 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800" id="menu-button" aria-expanded="true" aria-haspopup="true">
                
                  <i class="fa-solid fa-user"></i>  {{ request.user.username}}
                  
                  
                </button>
              </div>
            
              <!--
                Dropdown menu, show/hide based on menu state.
            
                Entering: "transition ease-out duration-100"
                  From: "transform opacity-0 scale-95"
                  To: "transform opacity-100 scale-100"
                Leaving: "transition ease-in duration-75"
                  From: "transform opacity-100 scale-100"
                  To: "transform opacity-0 scale-95"
              -->
              <div x-show="open" @click.away="open=false" class="absolute right-0 z-10 mt-2 w-56 origin-top-right rounded-md bg-white shadow-lg ring-1 ring-black ring-opacity-5 focus:outline-none" role="menu" aria-orientation="vertical" aria-labelledby="menu-button" tabindex="-1">
                <div class="py-1" role="none">
                  <!-- Active: "bg-gray-100 text-gray-900", Not Active: "text-gray-700" -->
                  <a href="{% url 'users:perfil_usuario' %}" class="text-gray-700 block px-4 py-2 text-sm" role="menuitem" tabindex="-1" id="menu-item-0">Perfil usuario</a>
                  <a href="{% url 'users:editar_perfil' %}" class="text-gray-700 block px-4 py-2 text-sm" role="menuitem" tabindex="-1" id="menu-item-1">Editar perfil usuario</a>
                  <a href="#" class="text-gray-700 block px-4 py-2 text-sm" role="menuitem" tabindex="-1" id="menu-item-2">License</a>
                  <a href="{% url 'account_logout' %}" class="text-gray-700 block w-full px-4 py-2 text-left text-sm" role="menuitem" tabindex="-1" id="menu-item-3">Cerrar sesión

                    </a>
                  
                </div>
              </div>
            </div>
            

            

          {% else %}

              <div class="flex items-center justify-center  px-20 py-10 rounded">
                
                
                <button type="button" class="text-white bg-blue-700 hover:bg-blue-800 focus:outline-none focus:ring-4 focus:ring-blue-300 font-medium rounded-full text-sm px-5 py-2.5 text-center mr-2 mb-2 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">
                  <a href="{% url 'account_signup' %}" class="text-base font-medium text-white p-2 m-2">Registrate</a>
                </button>

                
                <button type="button" class="text-white bg-blue-700 hover:bg-blue-800 focus:outline-none focus:ring-4 focus:ring-blue-300 font-medium rounded-full text-sm px-5 py-2.5 text-center mr-2 mb-2 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">
                  <a href="{% url 'account_login' %}" class="text-base font-medium text-white p-2 m-2">Login</a>
                </button>
              </div>
        

        {% endif %}
        </div>
        </div>
      </div>
      
      
    </nav>
    <!-- Mobile menu, show/hide based on menu open state. -->
    

templates/components/navbaradmin.html
{% load static %}
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container-fluid">
        <a href="{% url 'home' %}" class="flex items-center">
          <img class="h-8 w-auto" src="{% static 'images/logo.png' %}" alt="CSinfo">
          
        </a>
        <div class="items-center justify-between w-5/6 md:flex md:w-auto">
          <ul class="navbar-nav">          
            <li class="nav-item">
              <button type="button" class="btn btn-outline-secondary btn-rounded" data-mdb-ripple-color="dark">
                <a href="{% url 'users:listar' %}" class="block text-white rounded hover:bg-gray-100 md:hover:bg-transparent
               md:hover:text-blue-700 md:p-0 dark:text-white md:dark:hover:text-blue-500 dark:hover:bg-gray-700 md:dark:hover:bg-transparent dark:border-gray-700">Listar</a>
              </button>              
            </li>
            <li class="nav-item">
              <button type="button" class="btn btn-outline-secondary btn-rounded" data-mdb-ripple-color="dark">
              <a href="{% url 'users:agregar' %}" class="block text-white rounded hover:bg-gray-100 md:hover:bg-transparent
               md:hover:text-blue-700 md:p-0 dark:text-white md:dark:hover:text-blue-500 dark:hover:bg-gray-700 dark:hover:text-white
                md:dark:hover:bg-transparent dark:border-gray-700">Agregar</a>
              </button>
            </li>
            <li>
              <button type="button" class="btn btn-outline-secondary btn-rounded" data-mdb-ripple-color="dark">
              <a href="{% url 'users:actualizar' %}" class="block text-white rounded hover:bg-gray-100 md:hover:bg-transparent
               md:hover:text-blue-700 md:p-0 dark:text-white md:dark:hover:text-blue-500 dark:hover:bg-gray-700 dark:hover:text-white
                md:dark:hover:bg-transparent dark:border-gray-700">Actualizar</a>
              </button>
            </li>
            <li>
              <button type="button" class="btn btn-outline-secondary btn-rounded" data-mdb-ripple-color="dark">
              <a href="{% url 'users:eliminar' %}" class="block text-white rounded hover:bg-gray-100 md:hover:bg-transparent md:hover:text-blue-700 md:p-0 dark:text-white
               md:dark:hover:text-blue-500 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700">Eliminar</a>
              </button>
              </li>
              
            
          </ul>
        </div>
        
      
        <div x-data="{open: false}" class="flex items-center">
         
          <div class="flex -space-x-2">
            <div class="relative inline-block text-left">
              
              <div>
                <button @click="open=true" type="button" class="text-white bg-blue-700 hover:bg-blue-800 focus:outline-none focus:ring-4 focus:ring-blue-300 font-medium rounded-full text-sm px-5 py-2.5 text-center mr-2 mb-2 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800" id="menu-button" aria-expanded="true" aria-haspopup="true">
                
                  administrador
                  
                  
                </button>
              </div>
            
              <!--
                Dropdown menu, show/hide based on menu state.
            
                Entering: "transition ease-out duration-100"
                  From: "transform opacity-0 scale-95"
                  To: "transform opacity-100 scale-100"
                Leaving: "transition ease-in duration-75"
                  From: "transform opacity-100 scale-100"
                  To: "transform opacity-0 scale-95"
              -->
              <div x-show="open" @click.away="open=false" class="absolute right-0 z-10 mt-2 w-56 origin-top-right rounded-md bg-white shadow-lg ring-1 ring-black ring-opacity-5 focus:outline-none" role="menu" aria-orientation="vertical" aria-labelledby="menu-button" tabindex="-1">
                <div class="py-1" role="none">
                  <!-- Active: "bg-gray-100 text-gray-900", Not Active: "text-gray-700" -->{% comment %} 
                  <a href="{% url 'users:perfil_usuario' %}" class="text-gray-700 block px-4 py-2 text-sm" role="menuitem" tabindex="-1" id="menu-item-0">Perfil usuario</a>
                  <a href="{% url 'users:editar_perfil' %}" class="text-gray-700 block px-4 py-2 text-sm" role="menuitem" tabindex="-1" id="menu-item-1">Editar perfil usuario</a>
                  <a href="#" class="text-gray-700 block px-4 py-2 text-sm" role="menuitem" tabindex="-1" id="menu-item-2">License</a> {% endcomment %}
                  <a href="{% url 'account_logout' %}" class="text-gray-700 block w-full px-4 py-2 text-left text-sm" role="menuitem" tabindex="-1" id="menu-item-3">Cerrar sesión

                    </a>
                  
                </div>
              </div>
            </div>
            

            

        </div>
        </div>
      </div>
      
      
    </nav>
    <!-- Mobile menu, show/hide based on menu open state. -->
    

templates/components/navbarblog.html
{% load static %}


<nav class="navbar navbar-expand-lg navbar-dark bg-blue-400 rounded">
      <div class="container-fluid">
        <a href="{% url 'home' %}" class="flex items-center">
          <div>
            
          </div>
          
        </a>
        
      <div class="items-center justify-between w-5/6 md:flex md:w-auto">
        <ul class="navbar-nav">          
          <li class="nav-item">
            <button type="button" class="btn btn-outline-secondary btn-rounded" data-mdb-ripple-color="dark">
              <a href="{% url 'blog:create' %}" class="block text-black rounded hover:bg-gray-100 md:hover:bg-transparent
             md:hover:text-blue-700 md:p-0 dark:text-white md:dark:hover:text-blue-500 dark:hover:bg-gray-700 md:dark:hover:bg-transparent dark:border-gray-700">Crear post</a>
            </button>              
          </li>
          <li class="nav-item">
            <button type="button" class="btn btn-outline-secondary btn-rounded" data-mdb-ripple-color="dark">
            <a href="{% url 'blog:blog' %}" class="block text-black rounded hover:bg-gray-100 md:hover:bg-transparent
             md:hover:text-blue-700 md:p-0 dark:text-white md:dark:hover:text-blue-500 dark:hover:bg-gray-700 dark:hover:text-white
              md:dark:hover:bg-transparent dark:border-gray-700">Ver todos los post</a>
            </button>
          </li>
          
        </ul>
      </div>
      

      
      
    </nav>
    <!-- Mobile menu, show/hide based on menu open state. -->